// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FriendMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/AIYOU_G_P_BProtocolBuffers.h>
#else
 #import "AIYOU_G_P_BProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Friend;
@class PagePB;
@class TabInfo;
@class fullUserInfo;
@class response_30021_GroupKV;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum FriendCommand

typedef AIYOU_G_P_B_ENUM(FriendCommand) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  FriendCommand_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** proto3要求枚举第一个标记必须为0. */
  FriendCommand_PublicNull = 0,

  /** 响应成功 */
  FriendCommand_Success = 200,

  /** 响应失败 */
  FriendCommand_Fail = -200,

  /** 列表查询 */
  FriendCommand_Rt30000 = 30000,

  /** 好友上线提醒 */
  FriendCommand_Rt30001 = 30001,

  /** 好友申请 */
  FriendCommand_Rt30002 = 30002,

  /** 好友审核 */
  FriendCommand_Rt30003 = 30003,

  /** 添加敌人 */
  FriendCommand_Rt30004 = 30004,

  /** 添加黑名单 */
  FriendCommand_Rt30005 = 30005,

  /** 解除黑名单 */
  FriendCommand_Rt30006 = 30006,

  /** 解除敌人 */
  FriendCommand_Rt30007 = 30007,

  /** 解除好友关系 */
  FriendCommand_Rt30008 = 30008,

  /** 查询好友模块展示【我的好友】功能列表 */
  FriendCommand_Rt30010 = 30010,

  /** 推荐好友 */
  FriendCommand_Rt30011 = 30011,

  /** 推荐在线好友 */
  FriendCommand_Rt30012 = 30012,

  /** 推荐位置好友 */
  FriendCommand_Rt30013 = 30013,

  /** 【找朋友】功能列表 */
  FriendCommand_Rt30014 = 30014,

  /** 好友模块查找过滤 */
  FriendCommand_Rt30015 = 30015,

  /** 判断相互之间的关系 */
  FriendCommand_Rt30016 = 30016,

  /** 新建分组 */
  FriendCommand_Rt30017 = 30017,

  /** 删除分组.分组删除后，好友默认没有分组 */
  FriendCommand_Rt30018 = 30018,

  /** 修改分组名称 */
  FriendCommand_Rt30019 = 30019,

  /** 将好友移动到某个分组.如果取消分组，则groupID="" */
  FriendCommand_Rt30020 = 30020,

  /** 查询我的分组 */
  FriendCommand_Rt30021 = 30021,

  /** 修改好友备注 */
  FriendCommand_Rt30022 = 30022,

  /** 根据code查找用户及判断是否是好友 */
  FriendCommand_Rt30023 = 30023,

  /** 根据昵称或code查询用户 */
  FriendCommand_Rt30024 = 30024,

  /** 好友模块登录成功 */
  FriendCommand_Rt31000 = 31000,

  /** 尚未登录  response_unlogin */
  FriendCommand_Rt31001 = 31001,

  /** 缺少登录字段gameId,serverId,ticket,返回response_unlogin */
  FriendCommand_Rt31002 = 31002,

  /** 好友申请提醒 */
  FriendCommand_Msg32000 = 32000,

  /** 加好友成功提醒 */
  FriendCommand_Msg32001 = 32001,
};

AIYOU_G_P_BEnumDescriptor *FriendCommand_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL FriendCommand_IsValidValue(int32_t value);

#pragma mark - Enum QueryFriendListType

/** 好友列表类型 */
typedef AIYOU_G_P_B_ENUM(QueryFriendListType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  QueryFriendListType_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 我的未处理审核列表 */
  QueryFriendListType_Unaudit = 0,

  /** 我的已处理审核列表 */
  QueryFriendListType_Audited = 1,

  /** 我的审核列表 */
  QueryFriendListType_Audit = 2,

  /** 我的好友列表 */
  QueryFriendListType_Friend = 3,

  /** 我的黑名单 */
  QueryFriendListType_Black = 4,

  /** 我的敌人列表 */
  QueryFriendListType_Enemy = 5,

  /** 我的未处理申请列表 */
  QueryFriendListType_Unapply = 6,

  /** 我的已处理申请列表 */
  QueryFriendListType_Applyed = 7,

  /** 我的申请列表 */
  QueryFriendListType_Apply = 8,

  /** 推荐好友 */
  QueryFriendListType_Recommend = 9,

  /** 推荐在线好友 */
  QueryFriendListType_Onlinerecommend = 10,

  /** 根据地理位置推荐好友 */
  QueryFriendListType_Arearecommend = 11,
};

AIYOU_G_P_BEnumDescriptor *QueryFriendListType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL QueryFriendListType_IsValidValue(int32_t value);

#pragma mark - Enum REQType

/** 好友模块查找过滤 */
typedef AIYOU_G_P_B_ENUM(REQType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  REQType_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 好友 */
  REQType_ReqFriend = 0,

  /** 陌生人 */
  REQType_ReqEnemy = 1,

  /** 申请 */
  REQType_ReqApply = 2,

  /** 黑名单 */
  REQType_ReqBlack = 3,
};

AIYOU_G_P_BEnumDescriptor *REQType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL REQType_IsValidValue(int32_t value);

#pragma mark - Enum request_30003_AuditResultType

typedef AIYOU_G_P_B_ENUM(request_30003_AuditResultType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  request_30003_AuditResultType_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 通过 */
  request_30003_AuditResultType_Agree = 0,

  /** 拒绝 */
  request_30003_AuditResultType_Refuse = 1,

  /** 拉黑 */
  request_30003_AuditResultType_Black = 2,
};

AIYOU_G_P_BEnumDescriptor *request_30003_AuditResultType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL request_30003_AuditResultType_IsValidValue(int32_t value);

#pragma mark - Enum response_30016_FriendTypePB

typedef AIYOU_G_P_B_ENUM(response_30016_FriendTypePB) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  response_30016_FriendTypePB_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 好友 */
  response_30016_FriendTypePB_Friend = 0,

  /** 黑名单 */
  response_30016_FriendTypePB_Black = 1,

  /** 敌人 */
  response_30016_FriendTypePB_Enemy = 2,

  /** 没有关系 */
  response_30016_FriendTypePB_NoneRelation = 3,
};

AIYOU_G_P_BEnumDescriptor *response_30016_FriendTypePB_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL response_30016_FriendTypePB_IsValidValue(int32_t value);

#pragma mark - FriendMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (AIYOU_G_P_BExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c AIYOU_G_P_BExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface FriendMessageRoot : AIYOU_G_P_BRootObject
@end

#pragma mark - Friend

typedef AIYOU_G_P_B_ENUM(Friend_FieldNumber) {
  Friend_FieldNumber_FullUserInfo = 1,
  Friend_FieldNumber_Degree = 2,
  Friend_FieldNumber_AuditStatus = 3,
  Friend_FieldNumber_AuditResult = 4,
  Friend_FieldNumber_AuditId = 5,
  Friend_FieldNumber_Message = 6,
  Friend_FieldNumber_CreateTime = 7,
  Friend_FieldNumber_GroupId = 8,
  Friend_FieldNumber_GroupName = 9,
  Friend_FieldNumber_Comment = 10,
};

/**
 * 好友
 **/
@interface Friend : AIYOU_G_P_BMessage

/** 用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) fullUserInfo *fullUserInfo;
/** Test to see if @c fullUserInfo has been set. */
@property(nonatomic, readwrite) BOOL hasFullUserInfo;

/** 友好度 */
@property(nonatomic, readwrite) int32_t degree;

/** 申请状态：false 未处理  true已处理 */
@property(nonatomic, readwrite) BOOL auditStatus;

/** 申请处理结果  true 同意添加好友， false 拒绝添加好友 .  当auditStatus = false 这个值没意义 */
@property(nonatomic, readwrite) BOOL auditResult;

/** 当查审核列表时使用,在30003中使用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *auditId;

/** 请求添加好友是的说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** 创建时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *createTime;

/** 分组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 分组名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

/** 备注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *comment;

@end

#pragma mark - request_30000

typedef AIYOU_G_P_B_ENUM(request_30000_FieldNumber) {
  request_30000_FieldNumber_Type = 1,
  request_30000_FieldNumber_PagePb = 2,
};

/**
 * 获取列表
 **/
@interface request_30000 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) QueryFriendListType type;

/** 分页设置 */
@property(nonatomic, readwrite, strong, null_resettable) PagePB *pagePb;
/** Test to see if @c pagePb has been set. */
@property(nonatomic, readwrite) BOOL hasPagePb;

@end

/**
 * Fetches the raw value of a @c request_30000's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t request_30000_Type_RawValue(request_30000 *message);
/**
 * Sets the raw value of an @c request_30000's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setrequest_30000_Type_RawValue(request_30000 *message, int32_t value);

#pragma mark - response_30000

typedef AIYOU_G_P_B_ENUM(response_30000_FieldNumber) {
  response_30000_FieldNumber_ResultCode = 1,
  response_30000_FieldNumber_ResultMessage = 2,
  response_30000_FieldNumber_FriendsArray = 3,
  response_30000_FieldNumber_PagePb = 4,
  response_30000_FieldNumber_Type = 5,
};

@interface response_30000 : AIYOU_G_P_BMessage

/** 响应码：200 成功 -200 失败 */
@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 好友列表  黑名单列表  审核列表   敌人列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Friend*> *friendsArray;
/** The number of items in @c friendsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger friendsArray_Count;

/** 分页设置 */
@property(nonatomic, readwrite, strong, null_resettable) PagePB *pagePb;
/** Test to see if @c pagePb has been set. */
@property(nonatomic, readwrite) BOOL hasPagePb;

@property(nonatomic, readwrite) QueryFriendListType type;

@end

/**
 * Fetches the raw value of a @c response_30000's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t response_30000_Type_RawValue(response_30000 *message);
/**
 * Sets the raw value of an @c response_30000's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setresponse_30000_Type_RawValue(response_30000 *message, int32_t value);

#pragma mark - request_30001

/**
 * 上线通知
 **/
@interface request_30001 : AIYOU_G_P_BMessage

@end

#pragma mark - request_30002

typedef AIYOU_G_P_B_ENUM(request_30002_FieldNumber) {
  request_30002_FieldNumber_UserId = 1,
  request_30002_FieldNumber_Content = 2,
};

/**
 * 添加好友申请
 **/
@interface request_30002 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - response_30002

typedef AIYOU_G_P_B_ENUM(response_30002_FieldNumber) {
  response_30002_FieldNumber_ResultCode = 1,
  response_30002_FieldNumber_ResultMessage = 2,
  response_30002_FieldNumber_UserId = 3,
};

@interface response_30002 : AIYOU_G_P_BMessage

/** 响应码：200 成功 -200 失败 */
@property(nonatomic, readwrite) int32_t resultCode;

/** 响应说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

#pragma mark - request_30003

typedef AIYOU_G_P_B_ENUM(request_30003_FieldNumber) {
  request_30003_FieldNumber_AuditId = 1,
  request_30003_FieldNumber_AuditResultType = 2,
};

/**
 * 添加好友审核
 **/
@interface request_30003 : AIYOU_G_P_BMessage

/** 好友申请id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *auditId;

/** 审核类型 */
@property(nonatomic, readwrite) request_30003_AuditResultType auditResultType;

@end

/**
 * Fetches the raw value of a @c request_30003's @c auditResultType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t request_30003_AuditResultType_RawValue(request_30003 *message);
/**
 * Sets the raw value of an @c request_30003's @c auditResultType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setrequest_30003_AuditResultType_RawValue(request_30003 *message, int32_t value);

#pragma mark - request_30004

typedef AIYOU_G_P_B_ENUM(request_30004_FieldNumber) {
  request_30004_FieldNumber_UserId = 1,
  request_30004_FieldNumber_Content = 2,
};

/**
 * 添加敌人
 **/
@interface request_30004 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - request_30005

typedef AIYOU_G_P_B_ENUM(request_30005_FieldNumber) {
  request_30005_FieldNumber_UserId = 1,
  request_30005_FieldNumber_Content = 2,
};

/**
 * 添加黑名单
 **/
@interface request_30005 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - request_30006

typedef AIYOU_G_P_B_ENUM(request_30006_FieldNumber) {
  request_30006_FieldNumber_UserId = 1,
  request_30006_FieldNumber_Content = 2,
};

/**
 * 解除黑名单
 **/
@interface request_30006 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - request_30007

typedef AIYOU_G_P_B_ENUM(request_30007_FieldNumber) {
  request_30007_FieldNumber_UserId = 1,
  request_30007_FieldNumber_Content = 2,
};

/**
 * 解除敌人
 **/
@interface request_30007 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - request_30008

typedef AIYOU_G_P_B_ENUM(request_30008_FieldNumber) {
  request_30008_FieldNumber_UserId = 1,
  request_30008_FieldNumber_Content = 2,
};

/**
 * 解除好友关系
 **/
@interface request_30008 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - request_30010

/**
 * 【我的好友】功能列表查询
 **/
@interface request_30010 : AIYOU_G_P_BMessage

@end

#pragma mark - response_30010

typedef AIYOU_G_P_B_ENUM(response_30010_FieldNumber) {
  response_30010_FieldNumber_ResultCode = 1,
  response_30010_FieldNumber_ResultMessage = 2,
  response_30010_FieldNumber_TabInfoArray = 3,
};

@interface response_30010 : AIYOU_G_P_BMessage

/** 响应码：200 成功 -200 失败 */
@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TabInfo*> *tabInfoArray;
/** The number of items in @c tabInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tabInfoArray_Count;

@end

#pragma mark - TabInfo

typedef AIYOU_G_P_B_ENUM(TabInfo_FieldNumber) {
  TabInfo_FieldNumber_Type = 1,
  TabInfo_FieldNumber_Name = 2,
  TabInfo_FieldNumber_Num = 3,
  TabInfo_FieldNumber_MaxNum = 4,
};

/**
 * 界面展示[暂时提供:好友，黑名单，敌人，未审核列表]
 **/
@interface TabInfo : AIYOU_G_P_BMessage

/** 列表类型 */
@property(nonatomic, readwrite) QueryFriendListType type;

/** 对应名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 当前数 */
@property(nonatomic, readwrite) int32_t num;

/** 最大数,-1代表不用显示 */
@property(nonatomic, readwrite) int32_t maxNum;

@end

/**
 * Fetches the raw value of a @c TabInfo's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t TabInfo_Type_RawValue(TabInfo *message);
/**
 * Sets the raw value of an @c TabInfo's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetTabInfo_Type_RawValue(TabInfo *message, int32_t value);

#pragma mark - request_30011

typedef AIYOU_G_P_B_ENUM(request_30011_FieldNumber) {
  request_30011_FieldNumber_Num = 1,
};

/**
 * *
 * 推荐好友
 **/
@interface request_30011 : AIYOU_G_P_BMessage

/** 请求好友数量 */
@property(nonatomic, readwrite) int32_t num;

@end

#pragma mark - response_30011

typedef AIYOU_G_P_B_ENUM(response_30011_FieldNumber) {
  response_30011_FieldNumber_ResultCode = 1,
  response_30011_FieldNumber_ResultMessage = 2,
  response_30011_FieldNumber_UserInfoArray = 3,
};

@interface response_30011 : AIYOU_G_P_BMessage

/** 响应码：200 成功 -200 失败 */
@property(nonatomic, readwrite) int32_t resultCode;

/** 响应说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 推荐好友信息，不带资源属性 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<fullUserInfo*> *userInfoArray;
/** The number of items in @c userInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userInfoArray_Count;

@end

#pragma mark - request_30012

typedef AIYOU_G_P_B_ENUM(request_30012_FieldNumber) {
  request_30012_FieldNumber_N = 1,
};

/**
 * *
 * 推荐在线好友
 **/
@interface request_30012 : AIYOU_G_P_BMessage

/** 获取推荐数量 */
@property(nonatomic, readwrite) int32_t n;

@end

#pragma mark - response_30012

typedef AIYOU_G_P_B_ENUM(response_30012_FieldNumber) {
  response_30012_FieldNumber_ResultCode = 1,
  response_30012_FieldNumber_ResultMessage = 2,
  response_30012_FieldNumber_UserInfoArray = 3,
};

@interface response_30012 : AIYOU_G_P_BMessage

/** 响应码：200 成功 -200 失败 */
@property(nonatomic, readwrite) int32_t resultCode;

/** 响应说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 推荐好友信息，不带资源属性 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<fullUserInfo*> *userInfoArray;
/** The number of items in @c userInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userInfoArray_Count;

@end

#pragma mark - request_30013

typedef AIYOU_G_P_B_ENUM(request_30013_FieldNumber) {
  request_30013_FieldNumber_N = 1,
  request_30013_FieldNumber_Longitude = 2,
  request_30013_FieldNumber_Latitude = 3,
};

/**
 * *
 * 推荐位置好友
 **/
@interface request_30013 : AIYOU_G_P_BMessage

/** 获取推荐数量 */
@property(nonatomic, readwrite) int32_t n;

/** 经度 */
@property(nonatomic, readwrite) int32_t longitude;

/** 纬度 */
@property(nonatomic, readwrite) int32_t latitude;

@end

#pragma mark - response_30013

typedef AIYOU_G_P_B_ENUM(response_30013_FieldNumber) {
  response_30013_FieldNumber_ResultCode = 1,
  response_30013_FieldNumber_ResultMessage = 2,
  response_30013_FieldNumber_UserInfoArray = 3,
};

@interface response_30013 : AIYOU_G_P_BMessage

/** 响应码：200 成功 -200 失败 */
@property(nonatomic, readwrite) int32_t resultCode;

/** 响应说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 推荐好友信息，不带资源属性 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<fullUserInfo*> *userInfoArray;
/** The number of items in @c userInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userInfoArray_Count;

@end

#pragma mark - request_30014

/**
 * 【找朋友】功能列表查询
 **/
@interface request_30014 : AIYOU_G_P_BMessage

@end

#pragma mark - response_30014

typedef AIYOU_G_P_B_ENUM(response_30014_FieldNumber) {
  response_30014_FieldNumber_ResultCode = 1,
  response_30014_FieldNumber_ResultMessage = 2,
  response_30014_FieldNumber_TabInfoArray = 3,
};

@interface response_30014 : AIYOU_G_P_BMessage

/** 响应码：200 成功 -200 失败 */
@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TabInfo*> *tabInfoArray;
/** The number of items in @c tabInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger tabInfoArray_Count;

@end

#pragma mark - request_30015

typedef AIYOU_G_P_B_ENUM(request_30015_FieldNumber) {
  request_30015_FieldNumber_NickName = 1,
  request_30015_FieldNumber_ReqType = 2,
};

@interface request_30015 : AIYOU_G_P_BMessage

/** 好友角色名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

/** 过滤类型 */
@property(nonatomic, readwrite) REQType reqType;

@end

/**
 * Fetches the raw value of a @c request_30015's @c reqType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t request_30015_ReqType_RawValue(request_30015 *message);
/**
 * Sets the raw value of an @c request_30015's @c reqType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setrequest_30015_ReqType_RawValue(request_30015 *message, int32_t value);

#pragma mark - response_30015

typedef AIYOU_G_P_B_ENUM(response_30015_FieldNumber) {
  response_30015_FieldNumber_ResultCode = 1,
  response_30015_FieldNumber_ResultMessage = 2,
  response_30015_FieldNumber_ReqType = 3,
  response_30015_FieldNumber_FriendsArray = 4,
};

@interface response_30015 : AIYOU_G_P_BMessage

/** 响应码：200 成功 -200 失败 */
@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 过滤类型 */
@property(nonatomic, readwrite) REQType reqType;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Friend*> *friendsArray;
/** The number of items in @c friendsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger friendsArray_Count;

@end

/**
 * Fetches the raw value of a @c response_30015's @c reqType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t response_30015_ReqType_RawValue(response_30015 *message);
/**
 * Sets the raw value of an @c response_30015's @c reqType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setresponse_30015_ReqType_RawValue(response_30015 *message, int32_t value);

#pragma mark - request_30016

typedef AIYOU_G_P_B_ENUM(request_30016_FieldNumber) {
  request_30016_FieldNumber_TicketId = 1,
};

@interface request_30016 : AIYOU_G_P_BMessage

/** 对方角色ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ticketId;

@end

#pragma mark - response_30016

typedef AIYOU_G_P_B_ENUM(response_30016_FieldNumber) {
  response_30016_FieldNumber_ResultCode = 1,
  response_30016_FieldNumber_ResultMessage = 2,
  response_30016_FieldNumber_FriendType = 3,
};

@interface response_30016 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 好友关系 */
@property(nonatomic, readwrite) response_30016_FriendTypePB friendType;

@end

/**
 * Fetches the raw value of a @c response_30016's @c friendType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t response_30016_FriendType_RawValue(response_30016 *message);
/**
 * Sets the raw value of an @c response_30016's @c friendType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setresponse_30016_FriendType_RawValue(response_30016 *message, int32_t value);

#pragma mark - request_30017

typedef AIYOU_G_P_B_ENUM(request_30017_FieldNumber) {
  request_30017_FieldNumber_GroupName = 1,
};

/**
 * 新建分组
 **/
@interface request_30017 : AIYOU_G_P_BMessage

/** 分组名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

@end

#pragma mark - response_30017

typedef AIYOU_G_P_B_ENUM(response_30017_FieldNumber) {
  response_30017_FieldNumber_ResultCode = 1,
  response_30017_FieldNumber_ResultMessage = 2,
  response_30017_FieldNumber_GroupId = 3,
  response_30017_FieldNumber_GroupName = 4,
};

@interface response_30017 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 分组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 分组名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

@end

#pragma mark - request_30018

typedef AIYOU_G_P_B_ENUM(request_30018_FieldNumber) {
  request_30018_FieldNumber_GroupId = 1,
};

/**
 * 删除分组
 **/
@interface request_30018 : AIYOU_G_P_BMessage

/** 分组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@end

#pragma mark - response_30018

typedef AIYOU_G_P_B_ENUM(response_30018_FieldNumber) {
  response_30018_FieldNumber_ResultCode = 1,
  response_30018_FieldNumber_ResultMessage = 2,
};

@interface response_30018 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

@end

#pragma mark - request_30019

typedef AIYOU_G_P_B_ENUM(request_30019_FieldNumber) {
  request_30019_FieldNumber_GroupId = 1,
  request_30019_FieldNumber_GroupName = 2,
};

/**
 * 修改分组名称
 **/
@interface request_30019 : AIYOU_G_P_BMessage

/** 分组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 分组名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

@end

#pragma mark - response_30019

typedef AIYOU_G_P_B_ENUM(response_30019_FieldNumber) {
  response_30019_FieldNumber_ResultCode = 1,
  response_30019_FieldNumber_ResultMessage = 2,
  response_30019_FieldNumber_GroupId = 3,
  response_30019_FieldNumber_GroupName = 4,
};

@interface response_30019 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 分组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 分组名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

@end

#pragma mark - request_30020

typedef AIYOU_G_P_B_ENUM(request_30020_FieldNumber) {
  request_30020_FieldNumber_GroupId = 1,
  request_30020_FieldNumber_OtherRid = 2,
};

/**
 * 将好友移动到某个分组
 **/
@interface request_30020 : AIYOU_G_P_BMessage

/** 分组ID  取消分组groupID="" */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 好友角色ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *otherRid;

@end

#pragma mark - response_30020

typedef AIYOU_G_P_B_ENUM(response_30020_FieldNumber) {
  response_30020_FieldNumber_ResultCode = 1,
  response_30020_FieldNumber_ResultMessage = 2,
  response_30020_FieldNumber_OtherRid = 3,
  response_30020_FieldNumber_NewGroupId = 4,
};

@interface response_30020 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 好友角色ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *otherRid;

/** 新分组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *newGroupId NS_RETURNS_NOT_RETAINED;

@end

#pragma mark - request_30021

/**
 * 查询我的分组
 **/
@interface request_30021 : AIYOU_G_P_BMessage

@end

#pragma mark - response_30021

typedef AIYOU_G_P_B_ENUM(response_30021_FieldNumber) {
  response_30021_FieldNumber_ResultCode = 1,
  response_30021_FieldNumber_ResultMessage = 2,
  response_30021_FieldNumber_GroupKvsArray = 3,
};

@interface response_30021 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 分组集合 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<response_30021_GroupKV*> *groupKvsArray;
/** The number of items in @c groupKvsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger groupKvsArray_Count;

@end

#pragma mark - response_30021_GroupKV

typedef AIYOU_G_P_B_ENUM(response_30021_GroupKV_FieldNumber) {
  response_30021_GroupKV_FieldNumber_GroupId = 1,
  response_30021_GroupKV_FieldNumber_GroupName = 2,
};

@interface response_30021_GroupKV : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupName;

@end

#pragma mark - request_30022

typedef AIYOU_G_P_B_ENUM(request_30022_FieldNumber) {
  request_30022_FieldNumber_OtherRid = 1,
  request_30022_FieldNumber_Comment = 2,
};

/**
 * 修改好友备注
 **/
@interface request_30022 : AIYOU_G_P_BMessage

/** 好友角色ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *otherRid;

/** 好友备注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *comment;

@end

#pragma mark - response_30022

typedef AIYOU_G_P_B_ENUM(response_30022_FieldNumber) {
  response_30022_FieldNumber_ResultCode = 1,
  response_30022_FieldNumber_ResultMessage = 2,
  response_30022_FieldNumber_OtherRid = 3,
  response_30022_FieldNumber_Comment = 4,
};

@interface response_30022 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

/** 好友角色ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *otherRid;

/** 新分组备注 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *comment;

@end

#pragma mark - request_30023

typedef AIYOU_G_P_B_ENUM(request_30023_FieldNumber) {
  request_30023_FieldNumber_Code = 1,
};

/**
 * 根据code查找用户
 **/
@interface request_30023 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@end

#pragma mark - response_30023

typedef AIYOU_G_P_B_ENUM(response_30023_FieldNumber) {
  response_30023_FieldNumber_ResultCode = 1,
  response_30023_FieldNumber_ResultMessage = 2,
  response_30023_FieldNumber_User = 3,
  response_30023_FieldNumber_IsFriend = 4,
};

@interface response_30023 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

@property(nonatomic, readwrite, strong, null_resettable) fullUserInfo *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

/** 是否是好友 */
@property(nonatomic, readwrite) BOOL isFriend;

@end

#pragma mark - request_30024

typedef AIYOU_G_P_B_ENUM(request_30024_FieldNumber) {
  request_30024_FieldNumber_Para = 1,
};

/**
 * 根据昵称或code查找用户
 **/
@interface request_30024 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *para;

@end

#pragma mark - response_30024

typedef AIYOU_G_P_B_ENUM(response_30024_FieldNumber) {
  response_30024_FieldNumber_ResultCode = 1,
  response_30024_FieldNumber_ResultMessage = 2,
  response_30024_FieldNumber_UsersArray = 3,
};

@interface response_30024 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resultMessage;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<fullUserInfo*> *usersArray;
/** The number of items in @c usersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger usersArray_Count;

@end

#pragma mark - response_unLogin

typedef AIYOU_G_P_B_ENUM(response_unLogin_FieldNumber) {
  response_unLogin_FieldNumber_CommandId = 1,
};

@interface response_unLogin : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t commandId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
