// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/AIYOU_G_P_BProtocolBuffers.h>
#else
 #import "AIYOU_G_P_BProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Command;
@class GuildAttrPB;
@class GuildMemberInfo;
@class KVEntry;
@class fullUserInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum UserState

typedef AIYOU_G_P_B_ENUM(UserState) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  UserState_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 在线 */
  UserState_Online = 0,

  /** 离线 */
  UserState_Offline = 1,

  /** 备战 */
  UserState_Ready = 2,

  /** 战斗中 */
  UserState_Battle = 3,
};

AIYOU_G_P_BEnumDescriptor *UserState_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL UserState_IsValidValue(int32_t value);

#pragma mark - Enum Sex

/** 性别属性 */
typedef AIYOU_G_P_B_ENUM(Sex) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Sex_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 女性 */
  Sex_Female = 0,

  /** 男性 */
  Sex_Male = 1,

  /** 未知，当为未知是，不用更新 */
  Sex_NoneSex = 2,
};

AIYOU_G_P_BEnumDescriptor *Sex_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Sex_IsValidValue(int32_t value);

#pragma mark - Enum IconType

/** 头像类型属性 */
typedef AIYOU_G_P_B_ENUM(IconType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  IconType_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 本地头像 */
  IconType_Local = 0,

  /** 网络头像 */
  IconType_Online = 1,

  /** 未知,当为未知时，不用更新 */
  IconType_NoneType = 2,
};

AIYOU_G_P_BEnumDescriptor *IconType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL IconType_IsValidValue(int32_t value);

#pragma mark - Enum GuildPosition

typedef AIYOU_G_P_B_ENUM(GuildPosition) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  GuildPosition_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 会长 */
  GuildPosition_President = 0,

  /** 管理员 */
  GuildPosition_Manager = 1,

  /** 普通会员 */
  GuildPosition_Regular = 2,
};

AIYOU_G_P_BEnumDescriptor *GuildPosition_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL GuildPosition_IsValidValue(int32_t value);

#pragma mark - Enum BTStatusPB

/** 战斗状态，团战组用，公会状态 */
typedef AIYOU_G_P_B_ENUM(BTStatusPB) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  BTStatusPB_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 未开始 */
  BTStatusPB_StatusNotStart = 0,

  /** 备战 */
  BTStatusPB_StatusReady = 1,

  /** 进行中 */
  BTStatusPB_StatusUnderway = 2,

  /** 结束,更新的时候用 */
  BTStatusPB_StatusEnd = 3,
};

AIYOU_G_P_BEnumDescriptor *BTStatusPB_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL BTStatusPB_IsValidValue(int32_t value);

#pragma mark - Enum BTTypePB

/** 群组类型 */
typedef AIYOU_G_P_B_ENUM(BTTypePB) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  BTTypePB_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 聊天组类型 */
  BTTypePB_TypeChat = 0,

  /** 个人团战组类型 */
  BTTypePB_TypeBattle = 1,

  /** 公会团战群组 */
  BTTypePB_TypeGuildBattle = 2,
};

AIYOU_G_P_BEnumDescriptor *BTTypePB_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL BTTypePB_IsValidValue(int32_t value);

#pragma mark - Enum FSType

/** 好友偏好设置 */
typedef AIYOU_G_P_B_ENUM(FSType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  FSType_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 不更新 */
  FSType_Fsnone = 0,

  /** 自动添加 */
  FSType_Fsauto = 1,

  /** 需要审核 */
  FSType_Fsaudit = 2,

  /** 拒绝添加 */
  FSType_Fsforbiden = 3,
};

AIYOU_G_P_BEnumDescriptor *FSType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL FSType_IsValidValue(int32_t value);

#pragma mark - Enum RequestMessage_RequestType

typedef AIYOU_G_P_B_ENUM(RequestMessage_RequestType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  RequestMessage_RequestType_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 请求注册模块,用户注册需携带ID，昵称，头像,code */
  RequestMessage_RequestType_ClientRegister = 0,

  /** 请求用户模块 */
  RequestMessage_RequestType_ClientToUser = 1,

  /** 请求游戏模块 */
  RequestMessage_RequestType_ClientToGame = 2,

  /** 请求聊天模块 */
  RequestMessage_RequestType_ClientToImserver = 3,

  /** 请求分享模块 */
  RequestMessage_RequestType_ClientToShare = 4,

  /** 请求好友模块 */
  RequestMessage_RequestType_ClientToFriend = 5,

  /** 请求直播模块 */
  RequestMessage_RequestType_ClientToLive = 6,

  /** 视频会议 */
  RequestMessage_RequestType_ClientToMeeting = 7,

  /** 请求排行榜模块 */
  RequestMessage_RequestType_ClientToRank = 8,

  /** 请求公会模块 */
  RequestMessage_RequestType_ClientToGuild = 9,

  /** 请求背包模块 */
  RequestMessage_RequestType_ClientToKnapsack = 10,
  RequestMessage_RequestType_Heart = 999,
};

AIYOU_G_P_BEnumDescriptor *RequestMessage_RequestType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL RequestMessage_RequestType_IsValidValue(int32_t value);

#pragma mark - MessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (AIYOU_G_P_BExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c AIYOU_G_P_BExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MessageRoot : AIYOU_G_P_BRootObject
@end

#pragma mark - RequestMessage

typedef AIYOU_G_P_B_ENUM(RequestMessage_FieldNumber) {
  RequestMessage_FieldNumber_RequestType = 1,
  RequestMessage_FieldNumber_GameId = 2,
  RequestMessage_FieldNumber_ServerId = 3,
  RequestMessage_FieldNumber_Ticket = 4,
  RequestMessage_FieldNumber_Token = 5,
  RequestMessage_FieldNumber_Message = 6,
  RequestMessage_FieldNumber_IsH5 = 7,
};

/**
 * 请求参数包装类
 **/
@interface RequestMessage : AIYOU_G_P_BMessage

/** 请求类型 */
@property(nonatomic, readwrite) RequestMessage_RequestType requestType;

/** RequestMessage中属性gameId,serverId,ticket只有在网关注册时必填，其他请求不用填写 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ticket;

/** 第一次登录使用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** 是否是H5请求 */
@property(nonatomic, readwrite) BOOL isH5;

/** 请求，响应消息包装类 */
@property(nonatomic, readwrite, strong, null_resettable) Command *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

/**
 * Fetches the raw value of a @c RequestMessage's @c requestType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RequestMessage_RequestType_RawValue(RequestMessage *message);
/**
 * Sets the raw value of an @c RequestMessage's @c requestType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRequestMessage_RequestType_RawValue(RequestMessage *message, int32_t value);

#pragma mark - Command

typedef AIYOU_G_P_B_ENUM(Command_FieldNumber) {
  Command_FieldNumber_CommandId = 1,
  Command_FieldNumber_Message = 2,
};

@interface Command : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) int32_t commandId;

@property(nonatomic, readwrite, copy, null_resettable) NSData *message;

@end

#pragma mark - BroadcastMessage

typedef AIYOU_G_P_B_ENUM(BroadcastMessage_FieldNumber) {
  BroadcastMessage_FieldNumber_GameId = 1,
  BroadcastMessage_FieldNumber_ServerId = 2,
  BroadcastMessage_FieldNumber_UserIdsArray = 3,
  BroadcastMessage_FieldNumber_FilterIdsArray = 4,
  BroadcastMessage_FieldNumber_Message = 5,
};

@interface BroadcastMessage : AIYOU_G_P_BMessage

/** 可重复字段,接收消息的userId */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *userIdsArray;
/** The number of items in @c userIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userIdsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *filterIdsArray;
/** The number of items in @c filterIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger filterIdsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Command *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - GateInteractiveMessage

typedef AIYOU_G_P_B_ENUM(GateInteractiveMessage_FieldNumber) {
  GateInteractiveMessage_FieldNumber_GameId = 1,
  GateInteractiveMessage_FieldNumber_ServerId = 2,
  GateInteractiveMessage_FieldNumber_Ticket = 3,
  GateInteractiveMessage_FieldNumber_Message = 4,
};

/**
 * 网关间交互协议
 **/
@interface GateInteractiveMessage : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *gameId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ticket;

@property(nonatomic, readwrite, strong, null_resettable) Command *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - baseMessage

typedef AIYOU_G_P_B_ENUM(baseMessage_FieldNumber) {
  baseMessage_FieldNumber_Key = 1,
  baseMessage_FieldNumber_Name = 2,
  baseMessage_FieldNumber_Img = 3,
  baseMessage_FieldNumber_Value = 4,
  baseMessage_FieldNumber_IsVisible = 5,
};

/**
 * 资源基础信息
 **/
@interface baseMessage : AIYOU_G_P_BMessage

/** 资源key */
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

/** 资源名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 资源图片ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *img;

/** 资源数量 */
@property(nonatomic, readwrite) int64_t value;

/** 是否可见 */
@property(nonatomic, readwrite) BOOL isVisible;

@end

#pragma mark - KVEntry

typedef AIYOU_G_P_B_ENUM(KVEntry_FieldNumber) {
  KVEntry_FieldNumber_Key = 1,
  KVEntry_FieldNumber_Value = 2,
};

@interface KVEntry : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - BaseUserInfo

typedef AIYOU_G_P_B_ENUM(BaseUserInfo_FieldNumber) {
  BaseUserInfo_FieldNumber_TicketId = 1,
  BaseUserInfo_FieldNumber_NickName = 2,
  BaseUserInfo_FieldNumber_Icon = 3,
  BaseUserInfo_FieldNumber_Code = 4,
};

/**
 * 基础用户数据
 **/
@interface BaseUserInfo : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *ticketId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@end

#pragma mark - fullUserInfo

typedef AIYOU_G_P_B_ENUM(fullUserInfo_FieldNumber) {
  fullUserInfo_FieldNumber_TicketId = 1,
  fullUserInfo_FieldNumber_Nickname = 2,
  fullUserInfo_FieldNumber_Level = 3,
  fullUserInfo_FieldNumber_Sex = 4,
  fullUserInfo_FieldNumber_IconAddress = 6,
  fullUserInfo_FieldNumber_IconType = 7,
  fullUserInfo_FieldNumber_UserState = 8,
  fullUserInfo_FieldNumber_Os = 11,
  fullUserInfo_FieldNumber_Token = 12,
  fullUserInfo_FieldNumber_KvEntriesArray = 15,
  fullUserInfo_FieldNumber_ServerId = 16,
  fullUserInfo_FieldNumber_TicketCode = 17,
};

/**
 * 角色基础信息
 **/
@interface fullUserInfo : AIYOU_G_P_BMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ticketId;

/** 用户code */
@property(nonatomic, readwrite) int64_t ticketCode;

/** 用户所在服 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;

/** 昵称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

/** 等级 */
@property(nonatomic, readwrite) int32_t level;

/** 性别 */
@property(nonatomic, readwrite) Sex sex;

/**
 * 基础数值
 * repeated baseMessage baseMessage=5;
 * 头像地址
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *iconAddress;

/** 头像类型  0 本地头像，1 非本地头像 */
@property(nonatomic, readwrite) IconType iconType;

/** 用户状态 */
@property(nonatomic, readwrite) UserState userState;

/** 操作系统标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *os;

/** iOS 的设备标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<KVEntry*> *kvEntriesArray;
/** The number of items in @c kvEntriesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger kvEntriesArray_Count;

@end

/**
 * Fetches the raw value of a @c fullUserInfo's @c sex property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t fullUserInfo_Sex_RawValue(fullUserInfo *message);
/**
 * Sets the raw value of an @c fullUserInfo's @c sex property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetfullUserInfo_Sex_RawValue(fullUserInfo *message, int32_t value);

/**
 * Fetches the raw value of a @c fullUserInfo's @c iconType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t fullUserInfo_IconType_RawValue(fullUserInfo *message);
/**
 * Sets the raw value of an @c fullUserInfo's @c iconType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetfullUserInfo_IconType_RawValue(fullUserInfo *message, int32_t value);

/**
 * Fetches the raw value of a @c fullUserInfo's @c userState property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t fullUserInfo_UserState_RawValue(fullUserInfo *message);
/**
 * Sets the raw value of an @c fullUserInfo's @c userState property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetfullUserInfo_UserState_RawValue(fullUserInfo *message, int32_t value);

#pragma mark - PagePB

typedef AIYOU_G_P_B_ENUM(PagePB_FieldNumber) {
  PagePB_FieldNumber_PageNo = 1,
  PagePB_FieldNumber_PageSize = 2,
  PagePB_FieldNumber_TotalItems = 3,
  PagePB_FieldNumber_TotalPages = 4,
};

/**
 * 分页对象
 **/
@interface PagePB : AIYOU_G_P_BMessage

/** 当前页,从第一页开始 */
@property(nonatomic, readwrite) int32_t pageNo;

/** 每页条数 */
@property(nonatomic, readwrite) int32_t pageSize;

/** 总条数 */
@property(nonatomic, readwrite) int32_t totalItems;

/** 总页数 */
@property(nonatomic, readwrite) int32_t totalPages;

@end

#pragma mark - GuildMemberInfo

typedef AIYOU_G_P_B_ENUM(GuildMemberInfo_FieldNumber) {
  GuildMemberInfo_FieldNumber_FullUserInfo = 1,
  GuildMemberInfo_FieldNumber_Position = 2,
};

@interface GuildMemberInfo : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, strong, null_resettable) fullUserInfo *fullUserInfo;
/** Test to see if @c fullUserInfo has been set. */
@property(nonatomic, readwrite) BOOL hasFullUserInfo;

/** 公会职位:1 会长 2 管理员 3 普通会员 */
@property(nonatomic, readwrite) GuildPosition position;

@end

/**
 * Fetches the raw value of a @c GuildMemberInfo's @c position property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GuildMemberInfo_Position_RawValue(GuildMemberInfo *message);
/**
 * Sets the raw value of an @c GuildMemberInfo's @c position property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGuildMemberInfo_Position_RawValue(GuildMemberInfo *message, int32_t value);

#pragma mark - GuildPB

typedef AIYOU_G_P_B_ENUM(GuildPB_FieldNumber) {
  GuildPB_FieldNumber_Id_p = 1,
  GuildPB_FieldNumber_Name = 2,
  GuildPB_FieldNumber_GuildIcon = 3,
  GuildPB_FieldNumber_Creator = 4,
  GuildPB_FieldNumber_President = 5,
  GuildPB_FieldNumber_Description_p = 6,
  GuildPB_FieldNumber_CreateTime = 7,
  GuildPB_FieldNumber_GuildAttrPbArray = 8,
  GuildPB_FieldNumber_TeamId = 9,
  GuildPB_FieldNumber_BtStatusPb = 10,
  GuildPB_FieldNumber_Capacity = 11,
  GuildPB_FieldNumber_Used = 12,
};

@interface GuildPB : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 公会名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** */
@property(nonatomic, readwrite, copy, null_resettable) NSString *guildIcon;

/** 公会创建者 */
@property(nonatomic, readwrite, strong, null_resettable) GuildMemberInfo *creator;
/** Test to see if @c creator has been set. */
@property(nonatomic, readwrite) BOOL hasCreator;

/** 会长 */
@property(nonatomic, readwrite, strong, null_resettable) GuildMemberInfo *president;
/** Test to see if @c president has been set. */
@property(nonatomic, readwrite) BOOL hasPresident;

/** 公会说明 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

/** 创建时间 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *createTime;

/** 公会属性 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GuildAttrPB*> *guildAttrPbArray;
/** The number of items in @c guildAttrPbArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger guildAttrPbArray_Count;

/** 公会团战群组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *teamId;

/** 公会团战群组状态 */
@property(nonatomic, readwrite) BTStatusPB btStatusPb;

/** 最大容量 */
@property(nonatomic, readwrite) int32_t capacity;

/** 当前人数 */
@property(nonatomic, readwrite) int32_t used;

@end

/**
 * Fetches the raw value of a @c GuildPB's @c btStatusPb property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GuildPB_BtStatusPb_RawValue(GuildPB *message);
/**
 * Sets the raw value of an @c GuildPB's @c btStatusPb property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGuildPB_BtStatusPb_RawValue(GuildPB *message, int32_t value);

#pragma mark - GuildAttrPB

typedef AIYOU_G_P_B_ENUM(GuildAttrPB_FieldNumber) {
  GuildAttrPB_FieldNumber_Key = 1,
  GuildAttrPB_FieldNumber_Name = 2,
  GuildAttrPB_FieldNumber_Img = 3,
  GuildAttrPB_FieldNumber_Amount = 4,
  GuildAttrPB_FieldNumber_IsVisible = 5,
};

@interface GuildAttrPB : AIYOU_G_P_BMessage

/** key */
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

/** 名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 图标 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *img;

/** 数量 */
@property(nonatomic, readwrite) int64_t amount;

/** 是否可见 */
@property(nonatomic, readwrite) BOOL isVisible;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
