// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemCommand.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/AIYOU_G_P_BProtocolBuffers.h>
#else
 #import "AIYOU_G_P_BProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class response_2;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SystemCommandId

typedef AIYOU_G_P_B_ENUM(SystemCommandId) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  SystemCommandId_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 系统异常 */
  SystemCommandId_SystemError = 0,

  /** 飘字提示 */
  SystemCommandId_PublicErrorFloatage = 1,

  /** 弹窗提示 */
  SystemCommandId_PublicErrorWindows = 2,

  /** 第三方推送的交互消息 */
  SystemCommandId_PublicThirdpartMessage = 3,

  /** 系统消息 */
  SystemCommandId_SystemMessage = 4,

  /** 客户端向网关注册成功 */
  SystemCommandId_RegisterSuccess = 100,

  /** 强制下线，断开channel并发送强制下线通知 */
  SystemCommandId_ForcedOffline = 101,

  /** 系统维护，断开channel */
  SystemCommandId_SystemMaintenance = 102,

  /** 双线登录，断开channel并发送异地登录通知 */
  SystemCommandId_DoubleLogin = 103,

  /** 角色登录网关成功 */
  SystemCommandId_RegisterRidSuccess = 104,

  /** 角色未登录 */
  SystemCommandId_RegisterRidOffline = 105,

  /** uid未登录 */
  SystemCommandId_RegisterUidOffline = 106,

  /** 连接断开，需要重连 */
  SystemCommandId_RegisterAgain = 107,

  /** 网关注册失败，缺少必要字段 */
  SystemCommandId_RegisterMissingField = 108,

  /** 用户不合法 */
  SystemCommandId_ThirdpartyInvalid1 = 109,

  /** token不合法 */
  SystemCommandId_ThirdpartyInvalid2 = 110,

  /** token过期 */
  SystemCommandId_ThirdpartyInvalid3 = 111,

  /** 用户信息不存在 */
  SystemCommandId_ThirdpartyInvalid4 = 112,

  /** 第三方验证服务器异常 */
  SystemCommandId_ThirdpartyInvalid5 = 113,

  /** 心跳 */
  SystemCommandId_Heart = 999,
};

AIYOU_G_P_BEnumDescriptor *SystemCommandId_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SystemCommandId_IsValidValue(int32_t value);

#pragma mark - Enum ThirdPartMessageType

typedef AIYOU_G_P_B_ENUM(ThirdPartMessageType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ThirdPartMessageType_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  ThirdPartMessageType_WeixinShare = 0,
  ThirdPartMessageType_LiveComment = 1,
};

AIYOU_G_P_BEnumDescriptor *ThirdPartMessageType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ThirdPartMessageType_IsValidValue(int32_t value);

#pragma mark - Enum response_4_SMType

typedef AIYOU_G_P_B_ENUM(response_4_SMType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  response_4_SMType_AIYOU_G_P_BUnrecognizedEnumeratorValue = kAIYOU_G_P_BUnrecognizedEnumeratorValue,
  /** 管理员消息 */
  response_4_SMType_Sm100 = 0,

  /** 邀请消息 */
  response_4_SMType_Sm101 = 1,
};

AIYOU_G_P_BEnumDescriptor *response_4_SMType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL response_4_SMType_IsValidValue(int32_t value);

#pragma mark - SystemCommandRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (AIYOU_G_P_BExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c AIYOU_G_P_BExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SystemCommandRoot : AIYOU_G_P_BRootObject
@end

#pragma mark - response_4

typedef AIYOU_G_P_B_ENUM(response_4_FieldNumber) {
  response_4_FieldNumber_SmType = 1,
  response_4_FieldNumber_Payload = 2,
};

/**
 * 系统消息
 **/
@interface response_4 : AIYOU_G_P_BMessage

/** 消息ID */
@property(nonatomic, readwrite) response_4_SMType smType;

/** 消息体 */
@property(nonatomic, readwrite, strong, null_resettable) response_2 *payload;
/** Test to see if @c payload has been set. */
@property(nonatomic, readwrite) BOOL hasPayload;

@end

/**
 * Fetches the raw value of a @c response_4's @c smType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t response_4_SmType_RawValue(response_4 *message);
/**
 * Sets the raw value of an @c response_4's @c smType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setresponse_4_SmType_RawValue(response_4 *message, int32_t value);

#pragma mark - response_106

typedef AIYOU_G_P_B_ENUM(response_106_FieldNumber) {
  response_106_FieldNumber_CommandId = 1,
};

@interface response_106 : AIYOU_G_P_BMessage

/** session过期时的请求ID */
@property(nonatomic, readwrite) int32_t commandId;

@end

#pragma mark - response_1

typedef AIYOU_G_P_B_ENUM(response_1_FieldNumber) {
  response_1_FieldNumber_Content = 1,
  response_1_FieldNumber_Rtkey = 2,
};

/**
 * 公共协议——飘字
 **/
@interface response_1 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rtkey;

@end

#pragma mark - response_2

typedef AIYOU_G_P_B_ENUM(response_2_FieldNumber) {
  response_2_FieldNumber_Content = 1,
  response_2_FieldNumber_LeftButton = 2,
  response_2_FieldNumber_LeftURL = 3,
  response_2_FieldNumber_RightButton = 4,
  response_2_FieldNumber_RightURL = 5,
  response_2_FieldNumber_Rtkey = 6,
};

/**
 * 公共协议——弹板
 **/
@interface response_2 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *leftButton;

@property(nonatomic, readwrite, copy, null_resettable) NSString *leftURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rightButton;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rightURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rtkey;

@end

#pragma mark - response_3

typedef AIYOU_G_P_B_ENUM(response_3_FieldNumber) {
  response_3_FieldNumber_Type = 1,
  response_3_FieldNumber_Content = 2,
};

/**
 * 公共协议——推送的消息（通过第三方交互产生的消息，例如微信分享的点赞、阅读；直播频道的送花、回复等）
 **/
@interface response_3 : AIYOU_G_P_BMessage

@property(nonatomic, readwrite) ThirdPartMessageType type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

/**
 * Fetches the raw value of a @c response_3's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t response_3_Type_RawValue(response_3 *message);
/**
 * Sets the raw value of an @c response_3's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Setresponse_3_Type_RawValue(response_3 *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
