// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if AIYOU_G_P_B_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/AIYOU_G_P_BProtocolBuffers.h>
#else
 #import "AIYOU_G_P_BProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AIYOU_G_P_BWrappersRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (AIYOU_G_P_BExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c AIYOU_G_P_BExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AIYOU_G_P_BWrappersRoot : AIYOU_G_P_BRootObject
@end

#pragma mark - AIYOU_G_P_BDoubleValue

typedef AIYOU_G_P_B_ENUM(AIYOU_G_P_BDoubleValue_FieldNumber) {
  AIYOU_G_P_BDoubleValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `double`.
 *
 * The JSON representation for `DoubleValue` is JSON number.
 **/
@interface AIYOU_G_P_BDoubleValue : AIYOU_G_P_BMessage

/** The double value. */
@property(nonatomic, readwrite) double value;

@end

#pragma mark - AIYOU_G_P_BFloatValue

typedef AIYOU_G_P_B_ENUM(AIYOU_G_P_BFloatValue_FieldNumber) {
  AIYOU_G_P_BFloatValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `float`.
 *
 * The JSON representation for `FloatValue` is JSON number.
 **/
@interface AIYOU_G_P_BFloatValue : AIYOU_G_P_BMessage

/** The float value. */
@property(nonatomic, readwrite) float value;

@end

#pragma mark - AIYOU_G_P_BInt64Value

typedef AIYOU_G_P_B_ENUM(AIYOU_G_P_BInt64Value_FieldNumber) {
  AIYOU_G_P_BInt64Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `int64`.
 *
 * The JSON representation for `Int64Value` is JSON string.
 **/
@interface AIYOU_G_P_BInt64Value : AIYOU_G_P_BMessage

/** The int64 value. */
@property(nonatomic, readwrite) int64_t value;

@end

#pragma mark - AIYOU_G_P_BUInt64Value

typedef AIYOU_G_P_B_ENUM(AIYOU_G_P_BUInt64Value_FieldNumber) {
  AIYOU_G_P_BUInt64Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `uint64`.
 *
 * The JSON representation for `UInt64Value` is JSON string.
 **/
@interface AIYOU_G_P_BUInt64Value : AIYOU_G_P_BMessage

/** The uint64 value. */
@property(nonatomic, readwrite) uint64_t value;

@end

#pragma mark - AIYOU_G_P_BInt32Value

typedef AIYOU_G_P_B_ENUM(AIYOU_G_P_BInt32Value_FieldNumber) {
  AIYOU_G_P_BInt32Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `int32`.
 *
 * The JSON representation for `Int32Value` is JSON number.
 **/
@interface AIYOU_G_P_BInt32Value : AIYOU_G_P_BMessage

/** The int32 value. */
@property(nonatomic, readwrite) int32_t value;

@end

#pragma mark - AIYOU_G_P_BUInt32Value

typedef AIYOU_G_P_B_ENUM(AIYOU_G_P_BUInt32Value_FieldNumber) {
  AIYOU_G_P_BUInt32Value_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `uint32`.
 *
 * The JSON representation for `UInt32Value` is JSON number.
 **/
@interface AIYOU_G_P_BUInt32Value : AIYOU_G_P_BMessage

/** The uint32 value. */
@property(nonatomic, readwrite) uint32_t value;

@end

#pragma mark - AIYOU_G_P_BBoolValue

typedef AIYOU_G_P_B_ENUM(AIYOU_G_P_BBoolValue_FieldNumber) {
  AIYOU_G_P_BBoolValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `bool`.
 *
 * The JSON representation for `BoolValue` is JSON `true` and `false`.
 **/
@interface AIYOU_G_P_BBoolValue : AIYOU_G_P_BMessage

/** The bool value. */
@property(nonatomic, readwrite) BOOL value;

@end

#pragma mark - AIYOU_G_P_BStringValue

typedef AIYOU_G_P_B_ENUM(AIYOU_G_P_BStringValue_FieldNumber) {
  AIYOU_G_P_BStringValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `string`.
 *
 * The JSON representation for `StringValue` is JSON string.
 **/
@interface AIYOU_G_P_BStringValue : AIYOU_G_P_BMessage

/** The string value. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - AIYOU_G_P_BBytesValue

typedef AIYOU_G_P_B_ENUM(AIYOU_G_P_BBytesValue_FieldNumber) {
  AIYOU_G_P_BBytesValue_FieldNumber_Value = 1,
};

/**
 * Wrapper message for `bytes`.
 *
 * The JSON representation for `BytesValue` is JSON string.
 **/
@interface AIYOU_G_P_BBytesValue : AIYOU_G_P_BMessage

/** The bytes value. */
@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
